#!/usr/bin/env php
<?php

require __DIR__.'/src/AutoLoad.php';

stekel\AutoTest\autoload();

unset($argv[0]);

$subCommand = 'fancytest '.implode(' ', $argv);

if (file_exists('./vendor/bin/pest')) {
    $arguments = getopt('f:d:g:c:p', ['coverage', 'parallel']);

    $subCommand = (new stekel\AutoTest\Commands\Pest([
        'filter' => $arguments['f'] ?? null,
        'group' => $arguments['g'] ?? null,
        'directory' => $arguments['d'] ?? null,
        'parallel' => isset($arguments['parallel']) || isset($arguments['p']),
        'coverage' => isset($arguments['coverage']) || isset($arguments['c']),
        'basePath' => stekel\AutoTest\vendorDirectory(),
    ]))->get();
}

$autotest = new stekel\AutoTest\Commands\AutoTest([
    'subCommand' => $subCommand,
    'ignoredPaths' => [
        'vendor/*',
        'storage/*',
    ],
    'basePath' => stekel\AutoTest\vendorDirectory(),
]);

exit((new stekel\AutoTest\AutoTest($autotest))->fire());
