#!/usr/bin/env php
<?php

$autoloads = [
    __DIR__.'/vendor/autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/../../../vendor/autoload.php',
];

foreach ($autoloads as $autoload) {
    
    if (file_exists($autoload)) {
        
        require $autoload;

        break;
    }
}

$arguments = getopt('f:d:', ['no-coverage']);

$phpunit = new stekel\AutoTest\Commands\PhpUnit([
    'filter' => isset($arguments['f']) ? $arguments['f'] : null,
    'directory' => isset($arguments['d']) ? $arguments['d'] : null,
    'coverage' => isset($arguments['no-coverage']) ? !$arguments['no-coverage'] : null
]);

$config = stekel\AutoTest\Config::buildFromLaravel();
$config->setBasePath(realpath(__DIR__));

(new stekel\AutoTest\FancyTest($phpunit, $config))->fire();