#!/usr/bin/env php
<?php

require __DIR__.'/src/AutoLoad.php';

stekel\AutoTest\autoload();

$arguments = getopt('f:d:', ['coverage']);

$phpunit = new stekel\AutoTest\Commands\PhpUnit([
    'filter' => isset($arguments['f']) ? $arguments['f'] : null,
    'directory' => isset($arguments['d']) ? $arguments['d'] : null,
    'coverage' => isset($arguments['coverage']),
    'basePath' => realpath(__DIR__)
]);

$config = stekel\AutoTest\Config::buildFromLaravel();

(new stekel\AutoTest\FancyTest($phpunit, $config))->fire();